// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: materials/Blinn.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "materials/Blinn.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace atom {
namespace proto {
namespace materials {

namespace {

const ::google::protobuf::Descriptor* Blinn_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Blinn_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_materials_2fBlinn_2eproto() {
  protobuf_AddDesc_materials_2fBlinn_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "materials/Blinn.proto");
  GOOGLE_CHECK(file != NULL);
  Blinn_descriptor_ = file->message_type(0);
  static const int Blinn_offsets_[15] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, color_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, transparency_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, ambientcolor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, incandescence_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, bumpmap_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, diffuseamount_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, translucence_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, translucencedepth_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, translucencefocus_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, glowintensity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, eccentricity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, specularrolloff_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, specularcolor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, reflectivity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, reflectedcolor_),
  };
  Blinn_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Blinn_descriptor_,
      Blinn::default_instance_,
      Blinn_offsets_,
      -1,
      -1,
      -1,
      sizeof(Blinn),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blinn, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_materials_2fBlinn_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Blinn_descriptor_, &Blinn::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_materials_2fBlinn_2eproto() {
  delete Blinn::default_instance_;
  delete Blinn_reflection_;
}

void protobuf_AddDesc_materials_2fBlinn_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::atom::proto::materials::protobuf_AddDesc_materials_2fTexturedParameter_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025materials/Blinn.proto\022\024atom.proto.mate"
    "rials\032!materials/TexturedParameter.proto"
    "\"\226\007\n\005Blinn\0226\n\005Color\030\001 \001(\0132\'.atom.proto.m"
    "aterials.TexturedParameter\022=\n\014Transparen"
    "cy\030\002 \001(\0132\'.atom.proto.materials.Textured"
    "Parameter\022=\n\014AmbientColor\030\003 \001(\0132\'.atom.p"
    "roto.materials.TexturedParameter\022>\n\rInca"
    "ndescence\030\004 \001(\0132\'.atom.proto.materials.T"
    "exturedParameter\022\017\n\007BumpMap\030\005 \001(\t\022>\n\rDif"
    "fuseAmount\030\006 \001(\0132\'.atom.proto.materials."
    "TexturedParameter\022=\n\014Translucence\030\007 \001(\0132"
    "\'.atom.proto.materials.TexturedParameter"
    "\022B\n\021TranslucenceDepth\030\010 \001(\0132\'.atom.proto"
    ".materials.TexturedParameter\022B\n\021Transluc"
    "enceFocus\030\t \001(\0132\'.atom.proto.materials.T"
    "exturedParameter\022>\n\rGlowIntensity\030\n \001(\0132"
    "\'.atom.proto.materials.TexturedParameter"
    "\022=\n\014Eccentricity\030\013 \001(\0132\'.atom.proto.mate"
    "rials.TexturedParameter\022@\n\017SpecularRollO"
    "ff\030\014 \001(\0132\'.atom.proto.materials.Textured"
    "Parameter\022>\n\rSpecularColor\030\r \001(\0132\'.atom."
    "proto.materials.TexturedParameter\022=\n\014Ref"
    "lectivity\030\016 \001(\0132\'.atom.proto.materials.T"
    "exturedParameter\022\?\n\016ReflectedColor\030\017 \001(\013"
    "2\'.atom.proto.materials.TexturedParamete"
    "rb\006proto3", 1009);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "materials/Blinn.proto", &protobuf_RegisterTypes);
  Blinn::default_instance_ = new Blinn();
  Blinn::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_materials_2fBlinn_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_materials_2fBlinn_2eproto {
  StaticDescriptorInitializer_materials_2fBlinn_2eproto() {
    protobuf_AddDesc_materials_2fBlinn_2eproto();
  }
} static_descriptor_initializer_materials_2fBlinn_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Blinn::kColorFieldNumber;
const int Blinn::kTransparencyFieldNumber;
const int Blinn::kAmbientColorFieldNumber;
const int Blinn::kIncandescenceFieldNumber;
const int Blinn::kBumpMapFieldNumber;
const int Blinn::kDiffuseAmountFieldNumber;
const int Blinn::kTranslucenceFieldNumber;
const int Blinn::kTranslucenceDepthFieldNumber;
const int Blinn::kTranslucenceFocusFieldNumber;
const int Blinn::kGlowIntensityFieldNumber;
const int Blinn::kEccentricityFieldNumber;
const int Blinn::kSpecularRollOffFieldNumber;
const int Blinn::kSpecularColorFieldNumber;
const int Blinn::kReflectivityFieldNumber;
const int Blinn::kReflectedColorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Blinn::Blinn()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:atom.proto.materials.Blinn)
}

void Blinn::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  color_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  transparency_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  ambientcolor_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  incandescence_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  diffuseamount_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  translucence_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  translucencedepth_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  translucencefocus_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  glowintensity_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  eccentricity_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  specularrolloff_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  specularcolor_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  reflectivity_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
  reflectedcolor_ = const_cast< ::atom::proto::materials::TexturedParameter*>(&::atom::proto::materials::TexturedParameter::default_instance());
}

Blinn::Blinn(const Blinn& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:atom.proto.materials.Blinn)
}

void Blinn::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  color_ = NULL;
  transparency_ = NULL;
  ambientcolor_ = NULL;
  incandescence_ = NULL;
  bumpmap_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  diffuseamount_ = NULL;
  translucence_ = NULL;
  translucencedepth_ = NULL;
  translucencefocus_ = NULL;
  glowintensity_ = NULL;
  eccentricity_ = NULL;
  specularrolloff_ = NULL;
  specularcolor_ = NULL;
  reflectivity_ = NULL;
  reflectedcolor_ = NULL;
}

Blinn::~Blinn() {
  // @@protoc_insertion_point(destructor:atom.proto.materials.Blinn)
  SharedDtor();
}

void Blinn::SharedDtor() {
  bumpmap_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete color_;
    delete transparency_;
    delete ambientcolor_;
    delete incandescence_;
    delete diffuseamount_;
    delete translucence_;
    delete translucencedepth_;
    delete translucencefocus_;
    delete glowintensity_;
    delete eccentricity_;
    delete specularrolloff_;
    delete specularcolor_;
    delete reflectivity_;
    delete reflectedcolor_;
  }
}

void Blinn::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Blinn::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Blinn_descriptor_;
}

const Blinn& Blinn::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_materials_2fBlinn_2eproto();
  return *default_instance_;
}

Blinn* Blinn::default_instance_ = NULL;

Blinn* Blinn::New(::google::protobuf::Arena* arena) const {
  Blinn* n = new Blinn;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Blinn::Clear() {
  if (GetArenaNoVirtual() == NULL && color_ != NULL) delete color_;
  color_ = NULL;
  if (GetArenaNoVirtual() == NULL && transparency_ != NULL) delete transparency_;
  transparency_ = NULL;
  if (GetArenaNoVirtual() == NULL && ambientcolor_ != NULL) delete ambientcolor_;
  ambientcolor_ = NULL;
  if (GetArenaNoVirtual() == NULL && incandescence_ != NULL) delete incandescence_;
  incandescence_ = NULL;
  bumpmap_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && diffuseamount_ != NULL) delete diffuseamount_;
  diffuseamount_ = NULL;
  if (GetArenaNoVirtual() == NULL && translucence_ != NULL) delete translucence_;
  translucence_ = NULL;
  if (GetArenaNoVirtual() == NULL && translucencedepth_ != NULL) delete translucencedepth_;
  translucencedepth_ = NULL;
  if (GetArenaNoVirtual() == NULL && translucencefocus_ != NULL) delete translucencefocus_;
  translucencefocus_ = NULL;
  if (GetArenaNoVirtual() == NULL && glowintensity_ != NULL) delete glowintensity_;
  glowintensity_ = NULL;
  if (GetArenaNoVirtual() == NULL && eccentricity_ != NULL) delete eccentricity_;
  eccentricity_ = NULL;
  if (GetArenaNoVirtual() == NULL && specularrolloff_ != NULL) delete specularrolloff_;
  specularrolloff_ = NULL;
  if (GetArenaNoVirtual() == NULL && specularcolor_ != NULL) delete specularcolor_;
  specularcolor_ = NULL;
  if (GetArenaNoVirtual() == NULL && reflectivity_ != NULL) delete reflectivity_;
  reflectivity_ = NULL;
  if (GetArenaNoVirtual() == NULL && reflectedcolor_ != NULL) delete reflectedcolor_;
  reflectedcolor_ = NULL;
}

bool Blinn::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:atom.proto.materials.Blinn)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .atom.proto.materials.TexturedParameter Color = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_color()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_Transparency;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter Transparency = 2;
      case 2: {
        if (tag == 18) {
         parse_Transparency:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_transparency()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_AmbientColor;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter AmbientColor = 3;
      case 3: {
        if (tag == 26) {
         parse_AmbientColor:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ambientcolor()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_Incandescence;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter Incandescence = 4;
      case 4: {
        if (tag == 34) {
         parse_Incandescence:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_incandescence()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_BumpMap;
        break;
      }

      // optional string BumpMap = 5;
      case 5: {
        if (tag == 42) {
         parse_BumpMap:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_bumpmap()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->bumpmap().data(), this->bumpmap().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "atom.proto.materials.Blinn.BumpMap"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_DiffuseAmount;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter DiffuseAmount = 6;
      case 6: {
        if (tag == 50) {
         parse_DiffuseAmount:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_diffuseamount()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_Translucence;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter Translucence = 7;
      case 7: {
        if (tag == 58) {
         parse_Translucence:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_translucence()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_TranslucenceDepth;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter TranslucenceDepth = 8;
      case 8: {
        if (tag == 66) {
         parse_TranslucenceDepth:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_translucencedepth()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_TranslucenceFocus;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter TranslucenceFocus = 9;
      case 9: {
        if (tag == 74) {
         parse_TranslucenceFocus:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_translucencefocus()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(82)) goto parse_GlowIntensity;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter GlowIntensity = 10;
      case 10: {
        if (tag == 82) {
         parse_GlowIntensity:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_glowintensity()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_Eccentricity;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter Eccentricity = 11;
      case 11: {
        if (tag == 90) {
         parse_Eccentricity:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_eccentricity()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(98)) goto parse_SpecularRollOff;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter SpecularRollOff = 12;
      case 12: {
        if (tag == 98) {
         parse_SpecularRollOff:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_specularrolloff()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(106)) goto parse_SpecularColor;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter SpecularColor = 13;
      case 13: {
        if (tag == 106) {
         parse_SpecularColor:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_specularcolor()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(114)) goto parse_Reflectivity;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter Reflectivity = 14;
      case 14: {
        if (tag == 114) {
         parse_Reflectivity:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_reflectivity()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(122)) goto parse_ReflectedColor;
        break;
      }

      // optional .atom.proto.materials.TexturedParameter ReflectedColor = 15;
      case 15: {
        if (tag == 122) {
         parse_ReflectedColor:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_reflectedcolor()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:atom.proto.materials.Blinn)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:atom.proto.materials.Blinn)
  return false;
#undef DO_
}

void Blinn::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:atom.proto.materials.Blinn)
  // optional .atom.proto.materials.TexturedParameter Color = 1;
  if (this->has_color()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->color_, output);
  }

  // optional .atom.proto.materials.TexturedParameter Transparency = 2;
  if (this->has_transparency()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->transparency_, output);
  }

  // optional .atom.proto.materials.TexturedParameter AmbientColor = 3;
  if (this->has_ambientcolor()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->ambientcolor_, output);
  }

  // optional .atom.proto.materials.TexturedParameter Incandescence = 4;
  if (this->has_incandescence()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->incandescence_, output);
  }

  // optional string BumpMap = 5;
  if (this->bumpmap().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bumpmap().data(), this->bumpmap().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "atom.proto.materials.Blinn.BumpMap");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->bumpmap(), output);
  }

  // optional .atom.proto.materials.TexturedParameter DiffuseAmount = 6;
  if (this->has_diffuseamount()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *this->diffuseamount_, output);
  }

  // optional .atom.proto.materials.TexturedParameter Translucence = 7;
  if (this->has_translucence()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, *this->translucence_, output);
  }

  // optional .atom.proto.materials.TexturedParameter TranslucenceDepth = 8;
  if (this->has_translucencedepth()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, *this->translucencedepth_, output);
  }

  // optional .atom.proto.materials.TexturedParameter TranslucenceFocus = 9;
  if (this->has_translucencefocus()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, *this->translucencefocus_, output);
  }

  // optional .atom.proto.materials.TexturedParameter GlowIntensity = 10;
  if (this->has_glowintensity()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, *this->glowintensity_, output);
  }

  // optional .atom.proto.materials.TexturedParameter Eccentricity = 11;
  if (this->has_eccentricity()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, *this->eccentricity_, output);
  }

  // optional .atom.proto.materials.TexturedParameter SpecularRollOff = 12;
  if (this->has_specularrolloff()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, *this->specularrolloff_, output);
  }

  // optional .atom.proto.materials.TexturedParameter SpecularColor = 13;
  if (this->has_specularcolor()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      13, *this->specularcolor_, output);
  }

  // optional .atom.proto.materials.TexturedParameter Reflectivity = 14;
  if (this->has_reflectivity()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      14, *this->reflectivity_, output);
  }

  // optional .atom.proto.materials.TexturedParameter ReflectedColor = 15;
  if (this->has_reflectedcolor()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      15, *this->reflectedcolor_, output);
  }

  // @@protoc_insertion_point(serialize_end:atom.proto.materials.Blinn)
}

::google::protobuf::uint8* Blinn::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:atom.proto.materials.Blinn)
  // optional .atom.proto.materials.TexturedParameter Color = 1;
  if (this->has_color()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->color_, target);
  }

  // optional .atom.proto.materials.TexturedParameter Transparency = 2;
  if (this->has_transparency()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->transparency_, target);
  }

  // optional .atom.proto.materials.TexturedParameter AmbientColor = 3;
  if (this->has_ambientcolor()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, *this->ambientcolor_, target);
  }

  // optional .atom.proto.materials.TexturedParameter Incandescence = 4;
  if (this->has_incandescence()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, *this->incandescence_, target);
  }

  // optional string BumpMap = 5;
  if (this->bumpmap().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bumpmap().data(), this->bumpmap().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "atom.proto.materials.Blinn.BumpMap");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->bumpmap(), target);
  }

  // optional .atom.proto.materials.TexturedParameter DiffuseAmount = 6;
  if (this->has_diffuseamount()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, *this->diffuseamount_, target);
  }

  // optional .atom.proto.materials.TexturedParameter Translucence = 7;
  if (this->has_translucence()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        7, *this->translucence_, target);
  }

  // optional .atom.proto.materials.TexturedParameter TranslucenceDepth = 8;
  if (this->has_translucencedepth()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        8, *this->translucencedepth_, target);
  }

  // optional .atom.proto.materials.TexturedParameter TranslucenceFocus = 9;
  if (this->has_translucencefocus()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        9, *this->translucencefocus_, target);
  }

  // optional .atom.proto.materials.TexturedParameter GlowIntensity = 10;
  if (this->has_glowintensity()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        10, *this->glowintensity_, target);
  }

  // optional .atom.proto.materials.TexturedParameter Eccentricity = 11;
  if (this->has_eccentricity()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        11, *this->eccentricity_, target);
  }

  // optional .atom.proto.materials.TexturedParameter SpecularRollOff = 12;
  if (this->has_specularrolloff()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        12, *this->specularrolloff_, target);
  }

  // optional .atom.proto.materials.TexturedParameter SpecularColor = 13;
  if (this->has_specularcolor()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        13, *this->specularcolor_, target);
  }

  // optional .atom.proto.materials.TexturedParameter Reflectivity = 14;
  if (this->has_reflectivity()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        14, *this->reflectivity_, target);
  }

  // optional .atom.proto.materials.TexturedParameter ReflectedColor = 15;
  if (this->has_reflectedcolor()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        15, *this->reflectedcolor_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:atom.proto.materials.Blinn)
  return target;
}

int Blinn::ByteSize() const {
  int total_size = 0;

  // optional .atom.proto.materials.TexturedParameter Color = 1;
  if (this->has_color()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->color_);
  }

  // optional .atom.proto.materials.TexturedParameter Transparency = 2;
  if (this->has_transparency()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->transparency_);
  }

  // optional .atom.proto.materials.TexturedParameter AmbientColor = 3;
  if (this->has_ambientcolor()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->ambientcolor_);
  }

  // optional .atom.proto.materials.TexturedParameter Incandescence = 4;
  if (this->has_incandescence()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->incandescence_);
  }

  // optional string BumpMap = 5;
  if (this->bumpmap().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->bumpmap());
  }

  // optional .atom.proto.materials.TexturedParameter DiffuseAmount = 6;
  if (this->has_diffuseamount()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->diffuseamount_);
  }

  // optional .atom.proto.materials.TexturedParameter Translucence = 7;
  if (this->has_translucence()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->translucence_);
  }

  // optional .atom.proto.materials.TexturedParameter TranslucenceDepth = 8;
  if (this->has_translucencedepth()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->translucencedepth_);
  }

  // optional .atom.proto.materials.TexturedParameter TranslucenceFocus = 9;
  if (this->has_translucencefocus()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->translucencefocus_);
  }

  // optional .atom.proto.materials.TexturedParameter GlowIntensity = 10;
  if (this->has_glowintensity()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->glowintensity_);
  }

  // optional .atom.proto.materials.TexturedParameter Eccentricity = 11;
  if (this->has_eccentricity()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->eccentricity_);
  }

  // optional .atom.proto.materials.TexturedParameter SpecularRollOff = 12;
  if (this->has_specularrolloff()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->specularrolloff_);
  }

  // optional .atom.proto.materials.TexturedParameter SpecularColor = 13;
  if (this->has_specularcolor()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->specularcolor_);
  }

  // optional .atom.proto.materials.TexturedParameter Reflectivity = 14;
  if (this->has_reflectivity()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->reflectivity_);
  }

  // optional .atom.proto.materials.TexturedParameter ReflectedColor = 15;
  if (this->has_reflectedcolor()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->reflectedcolor_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Blinn::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Blinn* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Blinn>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Blinn::MergeFrom(const Blinn& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_color()) {
    mutable_color()->::atom::proto::materials::TexturedParameter::MergeFrom(from.color());
  }
  if (from.has_transparency()) {
    mutable_transparency()->::atom::proto::materials::TexturedParameter::MergeFrom(from.transparency());
  }
  if (from.has_ambientcolor()) {
    mutable_ambientcolor()->::atom::proto::materials::TexturedParameter::MergeFrom(from.ambientcolor());
  }
  if (from.has_incandescence()) {
    mutable_incandescence()->::atom::proto::materials::TexturedParameter::MergeFrom(from.incandescence());
  }
  if (from.bumpmap().size() > 0) {

    bumpmap_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bumpmap_);
  }
  if (from.has_diffuseamount()) {
    mutable_diffuseamount()->::atom::proto::materials::TexturedParameter::MergeFrom(from.diffuseamount());
  }
  if (from.has_translucence()) {
    mutable_translucence()->::atom::proto::materials::TexturedParameter::MergeFrom(from.translucence());
  }
  if (from.has_translucencedepth()) {
    mutable_translucencedepth()->::atom::proto::materials::TexturedParameter::MergeFrom(from.translucencedepth());
  }
  if (from.has_translucencefocus()) {
    mutable_translucencefocus()->::atom::proto::materials::TexturedParameter::MergeFrom(from.translucencefocus());
  }
  if (from.has_glowintensity()) {
    mutable_glowintensity()->::atom::proto::materials::TexturedParameter::MergeFrom(from.glowintensity());
  }
  if (from.has_eccentricity()) {
    mutable_eccentricity()->::atom::proto::materials::TexturedParameter::MergeFrom(from.eccentricity());
  }
  if (from.has_specularrolloff()) {
    mutable_specularrolloff()->::atom::proto::materials::TexturedParameter::MergeFrom(from.specularrolloff());
  }
  if (from.has_specularcolor()) {
    mutable_specularcolor()->::atom::proto::materials::TexturedParameter::MergeFrom(from.specularcolor());
  }
  if (from.has_reflectivity()) {
    mutable_reflectivity()->::atom::proto::materials::TexturedParameter::MergeFrom(from.reflectivity());
  }
  if (from.has_reflectedcolor()) {
    mutable_reflectedcolor()->::atom::proto::materials::TexturedParameter::MergeFrom(from.reflectedcolor());
  }
}

void Blinn::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Blinn::CopyFrom(const Blinn& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Blinn::IsInitialized() const {

  return true;
}

void Blinn::Swap(Blinn* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Blinn::InternalSwap(Blinn* other) {
  std::swap(color_, other->color_);
  std::swap(transparency_, other->transparency_);
  std::swap(ambientcolor_, other->ambientcolor_);
  std::swap(incandescence_, other->incandescence_);
  bumpmap_.Swap(&other->bumpmap_);
  std::swap(diffuseamount_, other->diffuseamount_);
  std::swap(translucence_, other->translucence_);
  std::swap(translucencedepth_, other->translucencedepth_);
  std::swap(translucencefocus_, other->translucencefocus_);
  std::swap(glowintensity_, other->glowintensity_);
  std::swap(eccentricity_, other->eccentricity_);
  std::swap(specularrolloff_, other->specularrolloff_);
  std::swap(specularcolor_, other->specularcolor_);
  std::swap(reflectivity_, other->reflectivity_);
  std::swap(reflectedcolor_, other->reflectedcolor_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Blinn::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Blinn_descriptor_;
  metadata.reflection = Blinn_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Blinn

// optional .atom.proto.materials.TexturedParameter Color = 1;
bool Blinn::has_color() const {
  return !_is_default_instance_ && color_ != NULL;
}
void Blinn::clear_color() {
  if (GetArenaNoVirtual() == NULL && color_ != NULL) delete color_;
  color_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::color() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.Color)
  return color_ != NULL ? *color_ : *default_instance_->color_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_color() {
  
  if (color_ == NULL) {
    color_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.Color)
  return color_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_color() {
  
  ::atom::proto::materials::TexturedParameter* temp = color_;
  color_ = NULL;
  return temp;
}
void Blinn::set_allocated_color(::atom::proto::materials::TexturedParameter* color) {
  delete color_;
  color_ = color;
  if (color) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.Color)
}

// optional .atom.proto.materials.TexturedParameter Transparency = 2;
bool Blinn::has_transparency() const {
  return !_is_default_instance_ && transparency_ != NULL;
}
void Blinn::clear_transparency() {
  if (GetArenaNoVirtual() == NULL && transparency_ != NULL) delete transparency_;
  transparency_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::transparency() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.Transparency)
  return transparency_ != NULL ? *transparency_ : *default_instance_->transparency_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_transparency() {
  
  if (transparency_ == NULL) {
    transparency_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.Transparency)
  return transparency_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_transparency() {
  
  ::atom::proto::materials::TexturedParameter* temp = transparency_;
  transparency_ = NULL;
  return temp;
}
void Blinn::set_allocated_transparency(::atom::proto::materials::TexturedParameter* transparency) {
  delete transparency_;
  transparency_ = transparency;
  if (transparency) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.Transparency)
}

// optional .atom.proto.materials.TexturedParameter AmbientColor = 3;
bool Blinn::has_ambientcolor() const {
  return !_is_default_instance_ && ambientcolor_ != NULL;
}
void Blinn::clear_ambientcolor() {
  if (GetArenaNoVirtual() == NULL && ambientcolor_ != NULL) delete ambientcolor_;
  ambientcolor_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::ambientcolor() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.AmbientColor)
  return ambientcolor_ != NULL ? *ambientcolor_ : *default_instance_->ambientcolor_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_ambientcolor() {
  
  if (ambientcolor_ == NULL) {
    ambientcolor_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.AmbientColor)
  return ambientcolor_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_ambientcolor() {
  
  ::atom::proto::materials::TexturedParameter* temp = ambientcolor_;
  ambientcolor_ = NULL;
  return temp;
}
void Blinn::set_allocated_ambientcolor(::atom::proto::materials::TexturedParameter* ambientcolor) {
  delete ambientcolor_;
  ambientcolor_ = ambientcolor;
  if (ambientcolor) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.AmbientColor)
}

// optional .atom.proto.materials.TexturedParameter Incandescence = 4;
bool Blinn::has_incandescence() const {
  return !_is_default_instance_ && incandescence_ != NULL;
}
void Blinn::clear_incandescence() {
  if (GetArenaNoVirtual() == NULL && incandescence_ != NULL) delete incandescence_;
  incandescence_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::incandescence() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.Incandescence)
  return incandescence_ != NULL ? *incandescence_ : *default_instance_->incandescence_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_incandescence() {
  
  if (incandescence_ == NULL) {
    incandescence_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.Incandescence)
  return incandescence_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_incandescence() {
  
  ::atom::proto::materials::TexturedParameter* temp = incandescence_;
  incandescence_ = NULL;
  return temp;
}
void Blinn::set_allocated_incandescence(::atom::proto::materials::TexturedParameter* incandescence) {
  delete incandescence_;
  incandescence_ = incandescence;
  if (incandescence) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.Incandescence)
}

// optional string BumpMap = 5;
void Blinn::clear_bumpmap() {
  bumpmap_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Blinn::bumpmap() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.BumpMap)
  return bumpmap_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Blinn::set_bumpmap(const ::std::string& value) {
  
  bumpmap_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:atom.proto.materials.Blinn.BumpMap)
}
 void Blinn::set_bumpmap(const char* value) {
  
  bumpmap_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:atom.proto.materials.Blinn.BumpMap)
}
 void Blinn::set_bumpmap(const char* value, size_t size) {
  
  bumpmap_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:atom.proto.materials.Blinn.BumpMap)
}
 ::std::string* Blinn::mutable_bumpmap() {
  
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.BumpMap)
  return bumpmap_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Blinn::release_bumpmap() {
  
  return bumpmap_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Blinn::set_allocated_bumpmap(::std::string* bumpmap) {
  if (bumpmap != NULL) {
    
  } else {
    
  }
  bumpmap_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bumpmap);
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.BumpMap)
}

// optional .atom.proto.materials.TexturedParameter DiffuseAmount = 6;
bool Blinn::has_diffuseamount() const {
  return !_is_default_instance_ && diffuseamount_ != NULL;
}
void Blinn::clear_diffuseamount() {
  if (GetArenaNoVirtual() == NULL && diffuseamount_ != NULL) delete diffuseamount_;
  diffuseamount_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::diffuseamount() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.DiffuseAmount)
  return diffuseamount_ != NULL ? *diffuseamount_ : *default_instance_->diffuseamount_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_diffuseamount() {
  
  if (diffuseamount_ == NULL) {
    diffuseamount_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.DiffuseAmount)
  return diffuseamount_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_diffuseamount() {
  
  ::atom::proto::materials::TexturedParameter* temp = diffuseamount_;
  diffuseamount_ = NULL;
  return temp;
}
void Blinn::set_allocated_diffuseamount(::atom::proto::materials::TexturedParameter* diffuseamount) {
  delete diffuseamount_;
  diffuseamount_ = diffuseamount;
  if (diffuseamount) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.DiffuseAmount)
}

// optional .atom.proto.materials.TexturedParameter Translucence = 7;
bool Blinn::has_translucence() const {
  return !_is_default_instance_ && translucence_ != NULL;
}
void Blinn::clear_translucence() {
  if (GetArenaNoVirtual() == NULL && translucence_ != NULL) delete translucence_;
  translucence_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::translucence() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.Translucence)
  return translucence_ != NULL ? *translucence_ : *default_instance_->translucence_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_translucence() {
  
  if (translucence_ == NULL) {
    translucence_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.Translucence)
  return translucence_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_translucence() {
  
  ::atom::proto::materials::TexturedParameter* temp = translucence_;
  translucence_ = NULL;
  return temp;
}
void Blinn::set_allocated_translucence(::atom::proto::materials::TexturedParameter* translucence) {
  delete translucence_;
  translucence_ = translucence;
  if (translucence) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.Translucence)
}

// optional .atom.proto.materials.TexturedParameter TranslucenceDepth = 8;
bool Blinn::has_translucencedepth() const {
  return !_is_default_instance_ && translucencedepth_ != NULL;
}
void Blinn::clear_translucencedepth() {
  if (GetArenaNoVirtual() == NULL && translucencedepth_ != NULL) delete translucencedepth_;
  translucencedepth_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::translucencedepth() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.TranslucenceDepth)
  return translucencedepth_ != NULL ? *translucencedepth_ : *default_instance_->translucencedepth_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_translucencedepth() {
  
  if (translucencedepth_ == NULL) {
    translucencedepth_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.TranslucenceDepth)
  return translucencedepth_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_translucencedepth() {
  
  ::atom::proto::materials::TexturedParameter* temp = translucencedepth_;
  translucencedepth_ = NULL;
  return temp;
}
void Blinn::set_allocated_translucencedepth(::atom::proto::materials::TexturedParameter* translucencedepth) {
  delete translucencedepth_;
  translucencedepth_ = translucencedepth;
  if (translucencedepth) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.TranslucenceDepth)
}

// optional .atom.proto.materials.TexturedParameter TranslucenceFocus = 9;
bool Blinn::has_translucencefocus() const {
  return !_is_default_instance_ && translucencefocus_ != NULL;
}
void Blinn::clear_translucencefocus() {
  if (GetArenaNoVirtual() == NULL && translucencefocus_ != NULL) delete translucencefocus_;
  translucencefocus_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::translucencefocus() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.TranslucenceFocus)
  return translucencefocus_ != NULL ? *translucencefocus_ : *default_instance_->translucencefocus_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_translucencefocus() {
  
  if (translucencefocus_ == NULL) {
    translucencefocus_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.TranslucenceFocus)
  return translucencefocus_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_translucencefocus() {
  
  ::atom::proto::materials::TexturedParameter* temp = translucencefocus_;
  translucencefocus_ = NULL;
  return temp;
}
void Blinn::set_allocated_translucencefocus(::atom::proto::materials::TexturedParameter* translucencefocus) {
  delete translucencefocus_;
  translucencefocus_ = translucencefocus;
  if (translucencefocus) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.TranslucenceFocus)
}

// optional .atom.proto.materials.TexturedParameter GlowIntensity = 10;
bool Blinn::has_glowintensity() const {
  return !_is_default_instance_ && glowintensity_ != NULL;
}
void Blinn::clear_glowintensity() {
  if (GetArenaNoVirtual() == NULL && glowintensity_ != NULL) delete glowintensity_;
  glowintensity_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::glowintensity() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.GlowIntensity)
  return glowintensity_ != NULL ? *glowintensity_ : *default_instance_->glowintensity_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_glowintensity() {
  
  if (glowintensity_ == NULL) {
    glowintensity_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.GlowIntensity)
  return glowintensity_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_glowintensity() {
  
  ::atom::proto::materials::TexturedParameter* temp = glowintensity_;
  glowintensity_ = NULL;
  return temp;
}
void Blinn::set_allocated_glowintensity(::atom::proto::materials::TexturedParameter* glowintensity) {
  delete glowintensity_;
  glowintensity_ = glowintensity;
  if (glowintensity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.GlowIntensity)
}

// optional .atom.proto.materials.TexturedParameter Eccentricity = 11;
bool Blinn::has_eccentricity() const {
  return !_is_default_instance_ && eccentricity_ != NULL;
}
void Blinn::clear_eccentricity() {
  if (GetArenaNoVirtual() == NULL && eccentricity_ != NULL) delete eccentricity_;
  eccentricity_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::eccentricity() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.Eccentricity)
  return eccentricity_ != NULL ? *eccentricity_ : *default_instance_->eccentricity_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_eccentricity() {
  
  if (eccentricity_ == NULL) {
    eccentricity_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.Eccentricity)
  return eccentricity_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_eccentricity() {
  
  ::atom::proto::materials::TexturedParameter* temp = eccentricity_;
  eccentricity_ = NULL;
  return temp;
}
void Blinn::set_allocated_eccentricity(::atom::proto::materials::TexturedParameter* eccentricity) {
  delete eccentricity_;
  eccentricity_ = eccentricity;
  if (eccentricity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.Eccentricity)
}

// optional .atom.proto.materials.TexturedParameter SpecularRollOff = 12;
bool Blinn::has_specularrolloff() const {
  return !_is_default_instance_ && specularrolloff_ != NULL;
}
void Blinn::clear_specularrolloff() {
  if (GetArenaNoVirtual() == NULL && specularrolloff_ != NULL) delete specularrolloff_;
  specularrolloff_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::specularrolloff() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.SpecularRollOff)
  return specularrolloff_ != NULL ? *specularrolloff_ : *default_instance_->specularrolloff_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_specularrolloff() {
  
  if (specularrolloff_ == NULL) {
    specularrolloff_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.SpecularRollOff)
  return specularrolloff_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_specularrolloff() {
  
  ::atom::proto::materials::TexturedParameter* temp = specularrolloff_;
  specularrolloff_ = NULL;
  return temp;
}
void Blinn::set_allocated_specularrolloff(::atom::proto::materials::TexturedParameter* specularrolloff) {
  delete specularrolloff_;
  specularrolloff_ = specularrolloff;
  if (specularrolloff) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.SpecularRollOff)
}

// optional .atom.proto.materials.TexturedParameter SpecularColor = 13;
bool Blinn::has_specularcolor() const {
  return !_is_default_instance_ && specularcolor_ != NULL;
}
void Blinn::clear_specularcolor() {
  if (GetArenaNoVirtual() == NULL && specularcolor_ != NULL) delete specularcolor_;
  specularcolor_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::specularcolor() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.SpecularColor)
  return specularcolor_ != NULL ? *specularcolor_ : *default_instance_->specularcolor_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_specularcolor() {
  
  if (specularcolor_ == NULL) {
    specularcolor_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.SpecularColor)
  return specularcolor_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_specularcolor() {
  
  ::atom::proto::materials::TexturedParameter* temp = specularcolor_;
  specularcolor_ = NULL;
  return temp;
}
void Blinn::set_allocated_specularcolor(::atom::proto::materials::TexturedParameter* specularcolor) {
  delete specularcolor_;
  specularcolor_ = specularcolor;
  if (specularcolor) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.SpecularColor)
}

// optional .atom.proto.materials.TexturedParameter Reflectivity = 14;
bool Blinn::has_reflectivity() const {
  return !_is_default_instance_ && reflectivity_ != NULL;
}
void Blinn::clear_reflectivity() {
  if (GetArenaNoVirtual() == NULL && reflectivity_ != NULL) delete reflectivity_;
  reflectivity_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::reflectivity() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.Reflectivity)
  return reflectivity_ != NULL ? *reflectivity_ : *default_instance_->reflectivity_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_reflectivity() {
  
  if (reflectivity_ == NULL) {
    reflectivity_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.Reflectivity)
  return reflectivity_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_reflectivity() {
  
  ::atom::proto::materials::TexturedParameter* temp = reflectivity_;
  reflectivity_ = NULL;
  return temp;
}
void Blinn::set_allocated_reflectivity(::atom::proto::materials::TexturedParameter* reflectivity) {
  delete reflectivity_;
  reflectivity_ = reflectivity;
  if (reflectivity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.Reflectivity)
}

// optional .atom.proto.materials.TexturedParameter ReflectedColor = 15;
bool Blinn::has_reflectedcolor() const {
  return !_is_default_instance_ && reflectedcolor_ != NULL;
}
void Blinn::clear_reflectedcolor() {
  if (GetArenaNoVirtual() == NULL && reflectedcolor_ != NULL) delete reflectedcolor_;
  reflectedcolor_ = NULL;
}
const ::atom::proto::materials::TexturedParameter& Blinn::reflectedcolor() const {
  // @@protoc_insertion_point(field_get:atom.proto.materials.Blinn.ReflectedColor)
  return reflectedcolor_ != NULL ? *reflectedcolor_ : *default_instance_->reflectedcolor_;
}
::atom::proto::materials::TexturedParameter* Blinn::mutable_reflectedcolor() {
  
  if (reflectedcolor_ == NULL) {
    reflectedcolor_ = new ::atom::proto::materials::TexturedParameter;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.materials.Blinn.ReflectedColor)
  return reflectedcolor_;
}
::atom::proto::materials::TexturedParameter* Blinn::release_reflectedcolor() {
  
  ::atom::proto::materials::TexturedParameter* temp = reflectedcolor_;
  reflectedcolor_ = NULL;
  return temp;
}
void Blinn::set_allocated_reflectedcolor(::atom::proto::materials::TexturedParameter* reflectedcolor) {
  delete reflectedcolor_;
  reflectedcolor_ = reflectedcolor;
  if (reflectedcolor) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.materials.Blinn.ReflectedColor)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace materials
}  // namespace proto
}  // namespace atom

// @@protoc_insertion_point(global_scope)
