// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: materials/MaterialType.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "materials/MaterialType.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace atom {
namespace proto {
namespace materials {

namespace {

const ::google::protobuf::EnumDescriptor* MaterialType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_materials_2fMaterialType_2eproto() {
  protobuf_AddDesc_materials_2fMaterialType_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "materials/MaterialType.proto");
  GOOGLE_CHECK(file != NULL);
  MaterialType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_materials_2fMaterialType_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_materials_2fMaterialType_2eproto() {
}

void protobuf_AddDesc_materials_2fMaterialType_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\034materials/MaterialType.proto\022\024atom.pro"
    "to.materials*\217\001\n\014MaterialType\022\030\n\024kMateri"
    "alTypeLambert\020\000\022\026\n\022kMaterialTypePhong\020\001\022"
    "\027\n\023kMaterialTypePhongE\020\002\022\026\n\022kMaterialTyp"
    "eBlinn\020\003\022\034\n\030kMaterialTypeAnisotropic\020\004b\006"
    "proto3", 206);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "materials/MaterialType.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_materials_2fMaterialType_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_materials_2fMaterialType_2eproto {
  StaticDescriptorInitializer_materials_2fMaterialType_2eproto() {
    protobuf_AddDesc_materials_2fMaterialType_2eproto();
  }
} static_descriptor_initializer_materials_2fMaterialType_2eproto_;
const ::google::protobuf::EnumDescriptor* MaterialType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MaterialType_descriptor_;
}
bool MaterialType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace materials
}  // namespace proto
}  // namespace atom

// @@protoc_insertion_point(global_scope)
