// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: materials/Anisotropic.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Atom.Proto.Materials {

  /// <summary>Holder for reflection information generated from materials/Anisotropic.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class AnisotropicReflection {

    #region Descriptor
    /// <summary>File descriptor for materials/Anisotropic.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AnisotropicReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChttYXRlcmlhbHMvQW5pc290cm9waWMucHJvdG8SFGF0b20ucHJvdG8ubWF0",
            "ZXJpYWxzGiFtYXRlcmlhbHMvVGV4dHVyZWRQYXJhbWV0ZXIucHJvdG8iwggK",
            "C0FuaXNvdHJvcGljEjYKBUNvbG9yGAEgASgLMicuYXRvbS5wcm90by5tYXRl",
            "cmlhbHMuVGV4dHVyZWRQYXJhbWV0ZXISPQoMVHJhbnNwYXJlbmN5GAIgASgL",
            "MicuYXRvbS5wcm90by5tYXRlcmlhbHMuVGV4dHVyZWRQYXJhbWV0ZXISPQoM",
            "QW1iaWVudENvbG9yGAMgASgLMicuYXRvbS5wcm90by5tYXRlcmlhbHMuVGV4",
            "dHVyZWRQYXJhbWV0ZXISPgoNSW5jYW5kZXNjZW5jZRgEIAEoCzInLmF0b20u",
            "cHJvdG8ubWF0ZXJpYWxzLlRleHR1cmVkUGFyYW1ldGVyEg8KB0J1bXBNYXAY",
            "BSABKAkSPgoNRGlmZnVzZUFtb3VudBgGIAEoCzInLmF0b20ucHJvdG8ubWF0",
            "ZXJpYWxzLlRleHR1cmVkUGFyYW1ldGVyEj0KDFRyYW5zbHVjZW5jZRgHIAEo",
            "CzInLmF0b20ucHJvdG8ubWF0ZXJpYWxzLlRleHR1cmVkUGFyYW1ldGVyEkIK",
            "EVRyYW5zbHVjZW5jZURlcHRoGAggASgLMicuYXRvbS5wcm90by5tYXRlcmlh",
            "bHMuVGV4dHVyZWRQYXJhbWV0ZXISQgoRVHJhbnNsdWNlbmNlRm9jdXMYCSAB",
            "KAsyJy5hdG9tLnByb3RvLm1hdGVyaWFscy5UZXh0dXJlZFBhcmFtZXRlchI+",
            "Cg1HbG93SW50ZW5zaXR5GAogASgLMicuYXRvbS5wcm90by5tYXRlcmlhbHMu",
            "VGV4dHVyZWRQYXJhbWV0ZXISNgoFQW5nbGUYCyABKAsyJy5hdG9tLnByb3Rv",
            "Lm1hdGVyaWFscy5UZXh0dXJlZFBhcmFtZXRlchI4CgdTcHJlYWRYGAwgASgL",
            "MicuYXRvbS5wcm90by5tYXRlcmlhbHMuVGV4dHVyZWRQYXJhbWV0ZXISOAoH",
            "U3ByZWFkWRgNIAEoCzInLmF0b20ucHJvdG8ubWF0ZXJpYWxzLlRleHR1cmVk",
            "UGFyYW1ldGVyEjoKCVJvdWdobmVzcxgOIAEoCzInLmF0b20ucHJvdG8ubWF0",
            "ZXJpYWxzLlRleHR1cmVkUGFyYW1ldGVyEj0KDEZyZXNuZWxJbmRleBgPIAEo",
            "CzInLmF0b20ucHJvdG8ubWF0ZXJpYWxzLlRleHR1cmVkUGFyYW1ldGVyEj4K",
            "DVNwZWN1bGFyQ29sb3IYECABKAsyJy5hdG9tLnByb3RvLm1hdGVyaWFscy5U",
            "ZXh0dXJlZFBhcmFtZXRlchI9CgxSZWZsZWN0aXZpdHkYESABKAsyJy5hdG9t",
            "LnByb3RvLm1hdGVyaWFscy5UZXh0dXJlZFBhcmFtZXRlchI/Cg5SZWZsZWN0",
            "ZWRDb2xvchgSIAEoCzInLmF0b20ucHJvdG8ubWF0ZXJpYWxzLlRleHR1cmVk",
            "UGFyYW1ldGVyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Atom.Proto.Materials.TexturedParameterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Atom.Proto.Materials.Anisotropic), global::Atom.Proto.Materials.Anisotropic.Parser, new[]{ "Color", "Transparency", "AmbientColor", "Incandescence", "BumpMap", "DiffuseAmount", "Translucence", "TranslucenceDepth", "TranslucenceFocus", "GlowIntensity", "Angle", "SpreadX", "SpreadY", "Roughness", "FresnelIndex", "SpecularColor", "Reflectivity", "ReflectedColor" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///
  ///  lambert stuff
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Anisotropic : pb::IMessage<Anisotropic> {
    private static readonly pb::MessageParser<Anisotropic> _parser = new pb::MessageParser<Anisotropic>(() => new Anisotropic());
    public static pb::MessageParser<Anisotropic> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::Atom.Proto.Materials.AnisotropicReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Anisotropic() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Anisotropic(Anisotropic other) : this() {
      Color = other.color_ != null ? other.Color.Clone() : null;
      Transparency = other.transparency_ != null ? other.Transparency.Clone() : null;
      AmbientColor = other.ambientColor_ != null ? other.AmbientColor.Clone() : null;
      Incandescence = other.incandescence_ != null ? other.Incandescence.Clone() : null;
      bumpMap_ = other.bumpMap_;
      DiffuseAmount = other.diffuseAmount_ != null ? other.DiffuseAmount.Clone() : null;
      Translucence = other.translucence_ != null ? other.Translucence.Clone() : null;
      TranslucenceDepth = other.translucenceDepth_ != null ? other.TranslucenceDepth.Clone() : null;
      TranslucenceFocus = other.translucenceFocus_ != null ? other.TranslucenceFocus.Clone() : null;
      GlowIntensity = other.glowIntensity_ != null ? other.GlowIntensity.Clone() : null;
      Angle = other.angle_ != null ? other.Angle.Clone() : null;
      SpreadX = other.spreadX_ != null ? other.SpreadX.Clone() : null;
      SpreadY = other.spreadY_ != null ? other.SpreadY.Clone() : null;
      Roughness = other.roughness_ != null ? other.Roughness.Clone() : null;
      FresnelIndex = other.fresnelIndex_ != null ? other.FresnelIndex.Clone() : null;
      SpecularColor = other.specularColor_ != null ? other.SpecularColor.Clone() : null;
      Reflectivity = other.reflectivity_ != null ? other.Reflectivity.Clone() : null;
      ReflectedColor = other.reflectedColor_ != null ? other.ReflectedColor.Clone() : null;
    }

    public Anisotropic Clone() {
      return new Anisotropic(this);
    }

    /// <summary>Field number for the "Color" field.</summary>
    public const int ColorFieldNumber = 1;
    private global::Atom.Proto.Materials.TexturedParameter color_;
    /// <summary>
    /// *&lt; Base color, as Color. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    /// <summary>Field number for the "Transparency" field.</summary>
    public const int TransparencyFieldNumber = 2;
    private global::Atom.Proto.Materials.TexturedParameter transparency_;
    /// <summary>
    /// *&lt; Transparent color, as Color. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter Transparency {
      get { return transparency_; }
      set {
        transparency_ = value;
      }
    }

    /// <summary>Field number for the "AmbientColor" field.</summary>
    public const int AmbientColorFieldNumber = 3;
    private global::Atom.Proto.Materials.TexturedParameter ambientColor_;
    /// <summary>
    /// *&lt; Ambient color, as Color. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter AmbientColor {
      get { return ambientColor_; }
      set {
        ambientColor_ = value;
      }
    }

    /// <summary>Field number for the "Incandescence" field.</summary>
    public const int IncandescenceFieldNumber = 4;
    private global::Atom.Proto.Materials.TexturedParameter incandescence_;
    /// <summary>
    /// *&lt; Incandescent color, as Color. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter Incandescence {
      get { return incandescence_; }
      set {
        incandescence_ = value;
      }
    }

    /// <summary>Field number for the "BumpMap" field.</summary>
    public const int BumpMapFieldNumber = 5;
    private string bumpMap_ = "";
    /// <summary>
    /// *&lt; Name of bump map texture. 
    /// </summary>
    public string BumpMap {
      get { return bumpMap_; }
      set {
        bumpMap_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DiffuseAmount" field.</summary>
    public const int DiffuseAmountFieldNumber = 6;
    private global::Atom.Proto.Materials.TexturedParameter diffuseAmount_;
    /// <summary>
    /// *&lt; Diffuse intensity, as float. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter DiffuseAmount {
      get { return diffuseAmount_; }
      set {
        diffuseAmount_ = value;
      }
    }

    /// <summary>Field number for the "Translucence" field.</summary>
    public const int TranslucenceFieldNumber = 7;
    private global::Atom.Proto.Materials.TexturedParameter translucence_;
    /// <summary>
    /// *&lt; Translucent amount, as float. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter Translucence {
      get { return translucence_; }
      set {
        translucence_ = value;
      }
    }

    /// <summary>Field number for the "TranslucenceDepth" field.</summary>
    public const int TranslucenceDepthFieldNumber = 8;
    private global::Atom.Proto.Materials.TexturedParameter translucenceDepth_;
    /// <summary>
    /// *&lt; Translucent depth, as float. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter TranslucenceDepth {
      get { return translucenceDepth_; }
      set {
        translucenceDepth_ = value;
      }
    }

    /// <summary>Field number for the "TranslucenceFocus" field.</summary>
    public const int TranslucenceFocusFieldNumber = 9;
    private global::Atom.Proto.Materials.TexturedParameter translucenceFocus_;
    /// <summary>
    /// *&lt; Translucent focus, as float. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter TranslucenceFocus {
      get { return translucenceFocus_; }
      set {
        translucenceFocus_ = value;
      }
    }

    /// <summary>Field number for the "GlowIntensity" field.</summary>
    public const int GlowIntensityFieldNumber = 10;
    private global::Atom.Proto.Materials.TexturedParameter glowIntensity_;
    /// <summary>
    /// *&lt; Glow intensity, as float. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter GlowIntensity {
      get { return glowIntensity_; }
      set {
        glowIntensity_ = value;
      }
    }

    /// <summary>Field number for the "Angle" field.</summary>
    public const int AngleFieldNumber = 11;
    private global::Atom.Proto.Materials.TexturedParameter angle_;
    /// <summary>
    /// *&lt; Angle, as float. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter Angle {
      get { return angle_; }
      set {
        angle_ = value;
      }
    }

    /// <summary>Field number for the "SpreadX" field.</summary>
    public const int SpreadXFieldNumber = 12;
    private global::Atom.Proto.Materials.TexturedParameter spreadX_;
    /// <summary>
    /// *&lt; Spread X, as float. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter SpreadX {
      get { return spreadX_; }
      set {
        spreadX_ = value;
      }
    }

    /// <summary>Field number for the "SpreadY" field.</summary>
    public const int SpreadYFieldNumber = 13;
    private global::Atom.Proto.Materials.TexturedParameter spreadY_;
    /// <summary>
    /// *&lt; Spread Y, as float. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter SpreadY {
      get { return spreadY_; }
      set {
        spreadY_ = value;
      }
    }

    /// <summary>Field number for the "Roughness" field.</summary>
    public const int RoughnessFieldNumber = 14;
    private global::Atom.Proto.Materials.TexturedParameter roughness_;
    /// <summary>
    /// *&lt; Surface roughness, as float. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter Roughness {
      get { return roughness_; }
      set {
        roughness_ = value;
      }
    }

    /// <summary>Field number for the "FresnelIndex" field.</summary>
    public const int FresnelIndexFieldNumber = 15;
    private global::Atom.Proto.Materials.TexturedParameter fresnelIndex_;
    /// <summary>
    /// *&lt; Fresnel index of refraction, as float. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter FresnelIndex {
      get { return fresnelIndex_; }
      set {
        fresnelIndex_ = value;
      }
    }

    /// <summary>Field number for the "SpecularColor" field.</summary>
    public const int SpecularColorFieldNumber = 16;
    private global::Atom.Proto.Materials.TexturedParameter specularColor_;
    /// <summary>
    /// *&lt; Specular color, as Color. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter SpecularColor {
      get { return specularColor_; }
      set {
        specularColor_ = value;
      }
    }

    /// <summary>Field number for the "Reflectivity" field.</summary>
    public const int ReflectivityFieldNumber = 17;
    private global::Atom.Proto.Materials.TexturedParameter reflectivity_;
    /// <summary>
    /// *&lt; Reflectivity amount, as float. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter Reflectivity {
      get { return reflectivity_; }
      set {
        reflectivity_ = value;
      }
    }

    /// <summary>Field number for the "ReflectedColor" field.</summary>
    public const int ReflectedColorFieldNumber = 18;
    private global::Atom.Proto.Materials.TexturedParameter reflectedColor_;
    /// <summary>
    /// *&lt; Reflected color, as Color. 
    /// </summary>
    public global::Atom.Proto.Materials.TexturedParameter ReflectedColor {
      get { return reflectedColor_; }
      set {
        reflectedColor_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Anisotropic);
    }

    public bool Equals(Anisotropic other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Color, other.Color)) return false;
      if (!object.Equals(Transparency, other.Transparency)) return false;
      if (!object.Equals(AmbientColor, other.AmbientColor)) return false;
      if (!object.Equals(Incandescence, other.Incandescence)) return false;
      if (BumpMap != other.BumpMap) return false;
      if (!object.Equals(DiffuseAmount, other.DiffuseAmount)) return false;
      if (!object.Equals(Translucence, other.Translucence)) return false;
      if (!object.Equals(TranslucenceDepth, other.TranslucenceDepth)) return false;
      if (!object.Equals(TranslucenceFocus, other.TranslucenceFocus)) return false;
      if (!object.Equals(GlowIntensity, other.GlowIntensity)) return false;
      if (!object.Equals(Angle, other.Angle)) return false;
      if (!object.Equals(SpreadX, other.SpreadX)) return false;
      if (!object.Equals(SpreadY, other.SpreadY)) return false;
      if (!object.Equals(Roughness, other.Roughness)) return false;
      if (!object.Equals(FresnelIndex, other.FresnelIndex)) return false;
      if (!object.Equals(SpecularColor, other.SpecularColor)) return false;
      if (!object.Equals(Reflectivity, other.Reflectivity)) return false;
      if (!object.Equals(ReflectedColor, other.ReflectedColor)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (color_ != null) hash ^= Color.GetHashCode();
      if (transparency_ != null) hash ^= Transparency.GetHashCode();
      if (ambientColor_ != null) hash ^= AmbientColor.GetHashCode();
      if (incandescence_ != null) hash ^= Incandescence.GetHashCode();
      if (BumpMap.Length != 0) hash ^= BumpMap.GetHashCode();
      if (diffuseAmount_ != null) hash ^= DiffuseAmount.GetHashCode();
      if (translucence_ != null) hash ^= Translucence.GetHashCode();
      if (translucenceDepth_ != null) hash ^= TranslucenceDepth.GetHashCode();
      if (translucenceFocus_ != null) hash ^= TranslucenceFocus.GetHashCode();
      if (glowIntensity_ != null) hash ^= GlowIntensity.GetHashCode();
      if (angle_ != null) hash ^= Angle.GetHashCode();
      if (spreadX_ != null) hash ^= SpreadX.GetHashCode();
      if (spreadY_ != null) hash ^= SpreadY.GetHashCode();
      if (roughness_ != null) hash ^= Roughness.GetHashCode();
      if (fresnelIndex_ != null) hash ^= FresnelIndex.GetHashCode();
      if (specularColor_ != null) hash ^= SpecularColor.GetHashCode();
      if (reflectivity_ != null) hash ^= Reflectivity.GetHashCode();
      if (reflectedColor_ != null) hash ^= ReflectedColor.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (color_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Color);
      }
      if (transparency_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Transparency);
      }
      if (ambientColor_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AmbientColor);
      }
      if (incandescence_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Incandescence);
      }
      if (BumpMap.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(BumpMap);
      }
      if (diffuseAmount_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(DiffuseAmount);
      }
      if (translucence_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Translucence);
      }
      if (translucenceDepth_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(TranslucenceDepth);
      }
      if (translucenceFocus_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(TranslucenceFocus);
      }
      if (glowIntensity_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(GlowIntensity);
      }
      if (angle_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Angle);
      }
      if (spreadX_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(SpreadX);
      }
      if (spreadY_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(SpreadY);
      }
      if (roughness_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(Roughness);
      }
      if (fresnelIndex_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(FresnelIndex);
      }
      if (specularColor_ != null) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(SpecularColor);
      }
      if (reflectivity_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(Reflectivity);
      }
      if (reflectedColor_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(ReflectedColor);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (color_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Color);
      }
      if (transparency_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transparency);
      }
      if (ambientColor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AmbientColor);
      }
      if (incandescence_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Incandescence);
      }
      if (BumpMap.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BumpMap);
      }
      if (diffuseAmount_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DiffuseAmount);
      }
      if (translucence_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Translucence);
      }
      if (translucenceDepth_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TranslucenceDepth);
      }
      if (translucenceFocus_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TranslucenceFocus);
      }
      if (glowIntensity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GlowIntensity);
      }
      if (angle_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angle);
      }
      if (spreadX_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpreadX);
      }
      if (spreadY_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpreadY);
      }
      if (roughness_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Roughness);
      }
      if (fresnelIndex_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FresnelIndex);
      }
      if (specularColor_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SpecularColor);
      }
      if (reflectivity_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Reflectivity);
      }
      if (reflectedColor_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ReflectedColor);
      }
      return size;
    }

    public void MergeFrom(Anisotropic other) {
      if (other == null) {
        return;
      }
      if (other.color_ != null) {
        if (color_ == null) {
          color_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        Color.MergeFrom(other.Color);
      }
      if (other.transparency_ != null) {
        if (transparency_ == null) {
          transparency_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        Transparency.MergeFrom(other.Transparency);
      }
      if (other.ambientColor_ != null) {
        if (ambientColor_ == null) {
          ambientColor_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        AmbientColor.MergeFrom(other.AmbientColor);
      }
      if (other.incandescence_ != null) {
        if (incandescence_ == null) {
          incandescence_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        Incandescence.MergeFrom(other.Incandescence);
      }
      if (other.BumpMap.Length != 0) {
        BumpMap = other.BumpMap;
      }
      if (other.diffuseAmount_ != null) {
        if (diffuseAmount_ == null) {
          diffuseAmount_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        DiffuseAmount.MergeFrom(other.DiffuseAmount);
      }
      if (other.translucence_ != null) {
        if (translucence_ == null) {
          translucence_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        Translucence.MergeFrom(other.Translucence);
      }
      if (other.translucenceDepth_ != null) {
        if (translucenceDepth_ == null) {
          translucenceDepth_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        TranslucenceDepth.MergeFrom(other.TranslucenceDepth);
      }
      if (other.translucenceFocus_ != null) {
        if (translucenceFocus_ == null) {
          translucenceFocus_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        TranslucenceFocus.MergeFrom(other.TranslucenceFocus);
      }
      if (other.glowIntensity_ != null) {
        if (glowIntensity_ == null) {
          glowIntensity_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        GlowIntensity.MergeFrom(other.GlowIntensity);
      }
      if (other.angle_ != null) {
        if (angle_ == null) {
          angle_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        Angle.MergeFrom(other.Angle);
      }
      if (other.spreadX_ != null) {
        if (spreadX_ == null) {
          spreadX_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        SpreadX.MergeFrom(other.SpreadX);
      }
      if (other.spreadY_ != null) {
        if (spreadY_ == null) {
          spreadY_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        SpreadY.MergeFrom(other.SpreadY);
      }
      if (other.roughness_ != null) {
        if (roughness_ == null) {
          roughness_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        Roughness.MergeFrom(other.Roughness);
      }
      if (other.fresnelIndex_ != null) {
        if (fresnelIndex_ == null) {
          fresnelIndex_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        FresnelIndex.MergeFrom(other.FresnelIndex);
      }
      if (other.specularColor_ != null) {
        if (specularColor_ == null) {
          specularColor_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        SpecularColor.MergeFrom(other.SpecularColor);
      }
      if (other.reflectivity_ != null) {
        if (reflectivity_ == null) {
          reflectivity_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        Reflectivity.MergeFrom(other.Reflectivity);
      }
      if (other.reflectedColor_ != null) {
        if (reflectedColor_ == null) {
          reflectedColor_ = new global::Atom.Proto.Materials.TexturedParameter();
        }
        ReflectedColor.MergeFrom(other.ReflectedColor);
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (color_ == null) {
              color_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(color_);
            break;
          }
          case 18: {
            if (transparency_ == null) {
              transparency_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(transparency_);
            break;
          }
          case 26: {
            if (ambientColor_ == null) {
              ambientColor_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(ambientColor_);
            break;
          }
          case 34: {
            if (incandescence_ == null) {
              incandescence_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(incandescence_);
            break;
          }
          case 42: {
            BumpMap = input.ReadString();
            break;
          }
          case 50: {
            if (diffuseAmount_ == null) {
              diffuseAmount_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(diffuseAmount_);
            break;
          }
          case 58: {
            if (translucence_ == null) {
              translucence_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(translucence_);
            break;
          }
          case 66: {
            if (translucenceDepth_ == null) {
              translucenceDepth_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(translucenceDepth_);
            break;
          }
          case 74: {
            if (translucenceFocus_ == null) {
              translucenceFocus_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(translucenceFocus_);
            break;
          }
          case 82: {
            if (glowIntensity_ == null) {
              glowIntensity_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(glowIntensity_);
            break;
          }
          case 90: {
            if (angle_ == null) {
              angle_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(angle_);
            break;
          }
          case 98: {
            if (spreadX_ == null) {
              spreadX_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(spreadX_);
            break;
          }
          case 106: {
            if (spreadY_ == null) {
              spreadY_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(spreadY_);
            break;
          }
          case 114: {
            if (roughness_ == null) {
              roughness_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(roughness_);
            break;
          }
          case 122: {
            if (fresnelIndex_ == null) {
              fresnelIndex_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(fresnelIndex_);
            break;
          }
          case 130: {
            if (specularColor_ == null) {
              specularColor_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(specularColor_);
            break;
          }
          case 138: {
            if (reflectivity_ == null) {
              reflectivity_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(reflectivity_);
            break;
          }
          case 146: {
            if (reflectedColor_ == null) {
              reflectedColor_ = new global::Atom.Proto.Materials.TexturedParameter();
            }
            input.ReadMessage(reflectedColor_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
