// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meshes/Mesh.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "meshes/Mesh.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace atom {
namespace proto {
namespace meshes {

namespace {

const ::google::protobuf::Descriptor* Mesh_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Mesh_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_meshes_2fMesh_2eproto() {
  protobuf_AddDesc_meshes_2fMesh_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "meshes/Mesh.proto");
  GOOGLE_CHECK(file != NULL);
  Mesh_descriptor_ = file->message_type(0);
  static const int Mesh_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, vertices_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, indices_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, texcoordsetnames_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, materialname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, world_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, initialvisibility_),
  };
  Mesh_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Mesh_descriptor_,
      Mesh::default_instance_,
      Mesh_offsets_,
      -1,
      -1,
      -1,
      sizeof(Mesh),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_meshes_2fMesh_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Mesh_descriptor_, &Mesh::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_meshes_2fMesh_2eproto() {
  delete Mesh::default_instance_;
  delete Mesh_reflection_;
}

void protobuf_AddDesc_meshes_2fMesh_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::atom::proto::protobuf_AddDesc_Vertex_2eproto();
  ::atom::proto::protobuf_AddDesc_Matrix_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021meshes/Mesh.proto\022\021atom.proto.meshes\032\014"
    "Vertex.proto\032\014Matrix.proto\"\275\001\n\004Mesh\022\014\n\004N"
    "ame\030\001 \001(\t\022$\n\010Vertices\030\002 \003(\0132\022.atom.proto"
    ".Vertex\022\023\n\007Indices\030\003 \003(\005B\002\020\001\022\030\n\020Texcoord"
    "SetNames\030\004 \003(\t\022\024\n\014MaterialName\030\005 \001(\t\022!\n\005"
    "World\030\006 \001(\0132\022.atom.proto.Matrix\022\031\n\021Initi"
    "alVisibility\030\007 \001(\010b\006proto3", 266);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "meshes/Mesh.proto", &protobuf_RegisterTypes);
  Mesh::default_instance_ = new Mesh();
  Mesh::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_meshes_2fMesh_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_meshes_2fMesh_2eproto {
  StaticDescriptorInitializer_meshes_2fMesh_2eproto() {
    protobuf_AddDesc_meshes_2fMesh_2eproto();
  }
} static_descriptor_initializer_meshes_2fMesh_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Mesh::kNameFieldNumber;
const int Mesh::kVerticesFieldNumber;
const int Mesh::kIndicesFieldNumber;
const int Mesh::kTexcoordSetNamesFieldNumber;
const int Mesh::kMaterialNameFieldNumber;
const int Mesh::kWorldFieldNumber;
const int Mesh::kInitialVisibilityFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Mesh::Mesh()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:atom.proto.meshes.Mesh)
}

void Mesh::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  world_ = const_cast< ::atom::proto::Matrix*>(&::atom::proto::Matrix::default_instance());
}

Mesh::Mesh(const Mesh& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:atom.proto.meshes.Mesh)
}

void Mesh::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  materialname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  world_ = NULL;
  initialvisibility_ = false;
}

Mesh::~Mesh() {
  // @@protoc_insertion_point(destructor:atom.proto.meshes.Mesh)
  SharedDtor();
}

void Mesh::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  materialname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete world_;
  }
}

void Mesh::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Mesh::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Mesh_descriptor_;
}

const Mesh& Mesh::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_meshes_2fMesh_2eproto();
  return *default_instance_;
}

Mesh* Mesh::default_instance_ = NULL;

Mesh* Mesh::New(::google::protobuf::Arena* arena) const {
  Mesh* n = new Mesh;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Mesh::Clear() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  materialname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && world_ != NULL) delete world_;
  world_ = NULL;
  initialvisibility_ = false;
  vertices_.Clear();
  indices_.Clear();
  texcoordsetnames_.Clear();
}

bool Mesh::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:atom.proto.meshes.Mesh)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string Name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "atom.proto.meshes.Mesh.Name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_Vertices;
        break;
      }

      // repeated .atom.proto.Vertex Vertices = 2;
      case 2: {
        if (tag == 18) {
         parse_Vertices:
          DO_(input->IncrementRecursionDepth());
         parse_loop_Vertices:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_vertices()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_Vertices;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(26)) goto parse_Indices;
        break;
      }

      // repeated int32 Indices = 3 [packed = true];
      case 3: {
        if (tag == 26) {
         parse_Indices:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_indices())));
        } else if (tag == 24) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 26, input, this->mutable_indices())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_TexcoordSetNames;
        break;
      }

      // repeated string TexcoordSetNames = 4;
      case 4: {
        if (tag == 34) {
         parse_TexcoordSetNames:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_texcoordsetnames()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->texcoordsetnames(this->texcoordsetnames_size() - 1).data(),
            this->texcoordsetnames(this->texcoordsetnames_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "atom.proto.meshes.Mesh.TexcoordSetNames"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_TexcoordSetNames;
        if (input->ExpectTag(42)) goto parse_MaterialName;
        break;
      }

      // optional string MaterialName = 5;
      case 5: {
        if (tag == 42) {
         parse_MaterialName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_materialname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->materialname().data(), this->materialname().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "atom.proto.meshes.Mesh.MaterialName"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_World;
        break;
      }

      // optional .atom.proto.Matrix World = 6;
      case 6: {
        if (tag == 50) {
         parse_World:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_world()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_InitialVisibility;
        break;
      }

      // optional bool InitialVisibility = 7;
      case 7: {
        if (tag == 56) {
         parse_InitialVisibility:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &initialvisibility_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:atom.proto.meshes.Mesh)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:atom.proto.meshes.Mesh)
  return false;
#undef DO_
}

void Mesh::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:atom.proto.meshes.Mesh)
  // optional string Name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "atom.proto.meshes.Mesh.Name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .atom.proto.Vertex Vertices = 2;
  for (unsigned int i = 0, n = this->vertices_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->vertices(i), output);
  }

  // repeated int32 Indices = 3 [packed = true];
  if (this->indices_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_indices_cached_byte_size_);
  }
  for (int i = 0; i < this->indices_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->indices(i), output);
  }

  // repeated string TexcoordSetNames = 4;
  for (int i = 0; i < this->texcoordsetnames_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->texcoordsetnames(i).data(), this->texcoordsetnames(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "atom.proto.meshes.Mesh.TexcoordSetNames");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->texcoordsetnames(i), output);
  }

  // optional string MaterialName = 5;
  if (this->materialname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->materialname().data(), this->materialname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "atom.proto.meshes.Mesh.MaterialName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->materialname(), output);
  }

  // optional .atom.proto.Matrix World = 6;
  if (this->has_world()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *this->world_, output);
  }

  // optional bool InitialVisibility = 7;
  if (this->initialvisibility() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->initialvisibility(), output);
  }

  // @@protoc_insertion_point(serialize_end:atom.proto.meshes.Mesh)
}

::google::protobuf::uint8* Mesh::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:atom.proto.meshes.Mesh)
  // optional string Name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "atom.proto.meshes.Mesh.Name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .atom.proto.Vertex Vertices = 2;
  for (unsigned int i = 0, n = this->vertices_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->vertices(i), target);
  }

  // repeated int32 Indices = 3 [packed = true];
  if (this->indices_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _indices_cached_byte_size_, target);
  }
  for (int i = 0; i < this->indices_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->indices(i), target);
  }

  // repeated string TexcoordSetNames = 4;
  for (int i = 0; i < this->texcoordsetnames_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->texcoordsetnames(i).data(), this->texcoordsetnames(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "atom.proto.meshes.Mesh.TexcoordSetNames");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->texcoordsetnames(i), target);
  }

  // optional string MaterialName = 5;
  if (this->materialname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->materialname().data(), this->materialname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "atom.proto.meshes.Mesh.MaterialName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->materialname(), target);
  }

  // optional .atom.proto.Matrix World = 6;
  if (this->has_world()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, *this->world_, target);
  }

  // optional bool InitialVisibility = 7;
  if (this->initialvisibility() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->initialvisibility(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:atom.proto.meshes.Mesh)
  return target;
}

int Mesh::ByteSize() const {
  int total_size = 0;

  // optional string Name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // optional string MaterialName = 5;
  if (this->materialname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->materialname());
  }

  // optional .atom.proto.Matrix World = 6;
  if (this->has_world()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->world_);
  }

  // optional bool InitialVisibility = 7;
  if (this->initialvisibility() != 0) {
    total_size += 1 + 1;
  }

  // repeated .atom.proto.Vertex Vertices = 2;
  total_size += 1 * this->vertices_size();
  for (int i = 0; i < this->vertices_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->vertices(i));
  }

  // repeated int32 Indices = 3 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->indices_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->indices(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _indices_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated string TexcoordSetNames = 4;
  total_size += 1 * this->texcoordsetnames_size();
  for (int i = 0; i < this->texcoordsetnames_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->texcoordsetnames(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Mesh::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Mesh* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Mesh>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Mesh::MergeFrom(const Mesh& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  vertices_.MergeFrom(from.vertices_);
  indices_.MergeFrom(from.indices_);
  texcoordsetnames_.MergeFrom(from.texcoordsetnames_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.materialname().size() > 0) {

    materialname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.materialname_);
  }
  if (from.has_world()) {
    mutable_world()->::atom::proto::Matrix::MergeFrom(from.world());
  }
  if (from.initialvisibility() != 0) {
    set_initialvisibility(from.initialvisibility());
  }
}

void Mesh::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Mesh::CopyFrom(const Mesh& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Mesh::IsInitialized() const {

  return true;
}

void Mesh::Swap(Mesh* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Mesh::InternalSwap(Mesh* other) {
  name_.Swap(&other->name_);
  vertices_.UnsafeArenaSwap(&other->vertices_);
  indices_.UnsafeArenaSwap(&other->indices_);
  texcoordsetnames_.UnsafeArenaSwap(&other->texcoordsetnames_);
  materialname_.Swap(&other->materialname_);
  std::swap(world_, other->world_);
  std::swap(initialvisibility_, other->initialvisibility_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Mesh::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Mesh_descriptor_;
  metadata.reflection = Mesh_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Mesh

// optional string Name = 1;
void Mesh::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Mesh::name() const {
  // @@protoc_insertion_point(field_get:atom.proto.meshes.Mesh.Name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Mesh::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:atom.proto.meshes.Mesh.Name)
}
 void Mesh::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:atom.proto.meshes.Mesh.Name)
}
 void Mesh::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:atom.proto.meshes.Mesh.Name)
}
 ::std::string* Mesh::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:atom.proto.meshes.Mesh.Name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Mesh::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Mesh::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:atom.proto.meshes.Mesh.Name)
}

// repeated .atom.proto.Vertex Vertices = 2;
int Mesh::vertices_size() const {
  return vertices_.size();
}
void Mesh::clear_vertices() {
  vertices_.Clear();
}
const ::atom::proto::Vertex& Mesh::vertices(int index) const {
  // @@protoc_insertion_point(field_get:atom.proto.meshes.Mesh.Vertices)
  return vertices_.Get(index);
}
::atom::proto::Vertex* Mesh::mutable_vertices(int index) {
  // @@protoc_insertion_point(field_mutable:atom.proto.meshes.Mesh.Vertices)
  return vertices_.Mutable(index);
}
::atom::proto::Vertex* Mesh::add_vertices() {
  // @@protoc_insertion_point(field_add:atom.proto.meshes.Mesh.Vertices)
  return vertices_.Add();
}
::google::protobuf::RepeatedPtrField< ::atom::proto::Vertex >*
Mesh::mutable_vertices() {
  // @@protoc_insertion_point(field_mutable_list:atom.proto.meshes.Mesh.Vertices)
  return &vertices_;
}
const ::google::protobuf::RepeatedPtrField< ::atom::proto::Vertex >&
Mesh::vertices() const {
  // @@protoc_insertion_point(field_list:atom.proto.meshes.Mesh.Vertices)
  return vertices_;
}

// repeated int32 Indices = 3 [packed = true];
int Mesh::indices_size() const {
  return indices_.size();
}
void Mesh::clear_indices() {
  indices_.Clear();
}
 ::google::protobuf::int32 Mesh::indices(int index) const {
  // @@protoc_insertion_point(field_get:atom.proto.meshes.Mesh.Indices)
  return indices_.Get(index);
}
 void Mesh::set_indices(int index, ::google::protobuf::int32 value) {
  indices_.Set(index, value);
  // @@protoc_insertion_point(field_set:atom.proto.meshes.Mesh.Indices)
}
 void Mesh::add_indices(::google::protobuf::int32 value) {
  indices_.Add(value);
  // @@protoc_insertion_point(field_add:atom.proto.meshes.Mesh.Indices)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Mesh::indices() const {
  // @@protoc_insertion_point(field_list:atom.proto.meshes.Mesh.Indices)
  return indices_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Mesh::mutable_indices() {
  // @@protoc_insertion_point(field_mutable_list:atom.proto.meshes.Mesh.Indices)
  return &indices_;
}

// repeated string TexcoordSetNames = 4;
int Mesh::texcoordsetnames_size() const {
  return texcoordsetnames_.size();
}
void Mesh::clear_texcoordsetnames() {
  texcoordsetnames_.Clear();
}
 const ::std::string& Mesh::texcoordsetnames(int index) const {
  // @@protoc_insertion_point(field_get:atom.proto.meshes.Mesh.TexcoordSetNames)
  return texcoordsetnames_.Get(index);
}
 ::std::string* Mesh::mutable_texcoordsetnames(int index) {
  // @@protoc_insertion_point(field_mutable:atom.proto.meshes.Mesh.TexcoordSetNames)
  return texcoordsetnames_.Mutable(index);
}
 void Mesh::set_texcoordsetnames(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:atom.proto.meshes.Mesh.TexcoordSetNames)
  texcoordsetnames_.Mutable(index)->assign(value);
}
 void Mesh::set_texcoordsetnames(int index, const char* value) {
  texcoordsetnames_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:atom.proto.meshes.Mesh.TexcoordSetNames)
}
 void Mesh::set_texcoordsetnames(int index, const char* value, size_t size) {
  texcoordsetnames_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:atom.proto.meshes.Mesh.TexcoordSetNames)
}
 ::std::string* Mesh::add_texcoordsetnames() {
  return texcoordsetnames_.Add();
}
 void Mesh::add_texcoordsetnames(const ::std::string& value) {
  texcoordsetnames_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:atom.proto.meshes.Mesh.TexcoordSetNames)
}
 void Mesh::add_texcoordsetnames(const char* value) {
  texcoordsetnames_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:atom.proto.meshes.Mesh.TexcoordSetNames)
}
 void Mesh::add_texcoordsetnames(const char* value, size_t size) {
  texcoordsetnames_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:atom.proto.meshes.Mesh.TexcoordSetNames)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
Mesh::texcoordsetnames() const {
  // @@protoc_insertion_point(field_list:atom.proto.meshes.Mesh.TexcoordSetNames)
  return texcoordsetnames_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
Mesh::mutable_texcoordsetnames() {
  // @@protoc_insertion_point(field_mutable_list:atom.proto.meshes.Mesh.TexcoordSetNames)
  return &texcoordsetnames_;
}

// optional string MaterialName = 5;
void Mesh::clear_materialname() {
  materialname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Mesh::materialname() const {
  // @@protoc_insertion_point(field_get:atom.proto.meshes.Mesh.MaterialName)
  return materialname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Mesh::set_materialname(const ::std::string& value) {
  
  materialname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:atom.proto.meshes.Mesh.MaterialName)
}
 void Mesh::set_materialname(const char* value) {
  
  materialname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:atom.proto.meshes.Mesh.MaterialName)
}
 void Mesh::set_materialname(const char* value, size_t size) {
  
  materialname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:atom.proto.meshes.Mesh.MaterialName)
}
 ::std::string* Mesh::mutable_materialname() {
  
  // @@protoc_insertion_point(field_mutable:atom.proto.meshes.Mesh.MaterialName)
  return materialname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Mesh::release_materialname() {
  
  return materialname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Mesh::set_allocated_materialname(::std::string* materialname) {
  if (materialname != NULL) {
    
  } else {
    
  }
  materialname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), materialname);
  // @@protoc_insertion_point(field_set_allocated:atom.proto.meshes.Mesh.MaterialName)
}

// optional .atom.proto.Matrix World = 6;
bool Mesh::has_world() const {
  return !_is_default_instance_ && world_ != NULL;
}
void Mesh::clear_world() {
  if (GetArenaNoVirtual() == NULL && world_ != NULL) delete world_;
  world_ = NULL;
}
const ::atom::proto::Matrix& Mesh::world() const {
  // @@protoc_insertion_point(field_get:atom.proto.meshes.Mesh.World)
  return world_ != NULL ? *world_ : *default_instance_->world_;
}
::atom::proto::Matrix* Mesh::mutable_world() {
  
  if (world_ == NULL) {
    world_ = new ::atom::proto::Matrix;
  }
  // @@protoc_insertion_point(field_mutable:atom.proto.meshes.Mesh.World)
  return world_;
}
::atom::proto::Matrix* Mesh::release_world() {
  
  ::atom::proto::Matrix* temp = world_;
  world_ = NULL;
  return temp;
}
void Mesh::set_allocated_world(::atom::proto::Matrix* world) {
  delete world_;
  world_ = world;
  if (world) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:atom.proto.meshes.Mesh.World)
}

// optional bool InitialVisibility = 7;
void Mesh::clear_initialvisibility() {
  initialvisibility_ = false;
}
 bool Mesh::initialvisibility() const {
  // @@protoc_insertion_point(field_get:atom.proto.meshes.Mesh.InitialVisibility)
  return initialvisibility_;
}
 void Mesh::set_initialvisibility(bool value) {
  
  initialvisibility_ = value;
  // @@protoc_insertion_point(field_set:atom.proto.meshes.Mesh.InitialVisibility)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace meshes
}  // namespace proto
}  // namespace atom

// @@protoc_insertion_point(global_scope)
